SPACE = '⬜'
ROBOT = '🐺'
OBSTA = '🪨'
DESTINO='🔴'
CAJA ='📦'


tablero = (
    [OBSTA, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, OBSTA, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, SPACE, SPACE, CAJA, SPACE],
    [SPACE, SPACE, DESTINO, ROBOT, OBSTA, SPACE, SPACE],
    [OBSTA, SPACE, SPACE, SPACE, SPACE, SPACE, SPACE],
    [SPACE, SPACE, SPACE, OBSTA, SPACE, SPACE, SPACE],
 )